MODE:
  MIM: True
  MLM: True
  CODEBOOK: True
MODEL:
  WEIGHT: "imagenet"
  FREEZE_TEXT: False
  FREEZE_VISUAL: False
  VISUAL_MODEL: "vit_base_patch16_224"
  TEXTUAL_MODEL: "bert"
  IMS_PER_BN: 64
  BERT:
    MAX_LENGTH: 100
    POOL: False
    OUTPUT_ALL: True
#  NUM_CLASSES: 11003  # cuhkpedes
  NUM_CLASSES: 29000  # flickr30k
#  NUM_CLASSES: 5894  # cub train
#  NUM_CLASSES: 8855  # cub trainval
#  NUM_CLASSES: 5878  # flowers train
#  NUM_CLASSES: 7034  # flowers trainval
#  NUM_CLASSES: 82783  # mscoco train
#  NUM_CLASSES: 113287  # mscoco trainval
  NUM_PARTS: 5
  RESNET:
    RES5_STRIDE: 1
    PRETRAINED: "pretrained/checkpoints/resnet50-19c8e357.pth"
  VIT:
    MODE: "all"
    CKPT: "pretrained/checkpoints/B_16-i21k-300ep-lr_0.001-aug_medium1-wd_0.1-do_0.0-sd_0.0.npz"
  EMBEDDING:
    EMBED_HEAD: 'baseline'
    FEATURE_SIZE: 512
    DROPOUT_PROB: 0.0
    LOSS_TYPE: [ "cmpm_loss", "cmpc_loss" ]
    LOSS_WEIGHT: [ 1., 1. ]
    VISUAL_POOL: 'avgpool'
    TEXTUAL_POOL: 'maxpool'
  LOSSES:
    CE:
      EPSILON: 0.1
INPUT:
  HEIGHT: 224
  WIDTH: 224
  FLIP:
    ENABLED: True
  PADDING:
    ENABLED: True
DATALOADER:
  EN_SAMPLER: "TrainingSampler"
DATASETS:
  TRAIN: ("flickr30k_train", )
  VAL: ("flickr30k_val", "flickr30k_test", )
  TEST: ("flickr30k_test", )
  USE_ONEHOT: False
  USE_SEG: False
  USE_ATT: False
SOLVER:
  AMP: True
  IMS_PER_BATCH: 64
  NUM_EPOCHS: 120
  BASE_LR: 0.0002
  WEIGHT_DECAY: 0.
  WEIGHT_DECAY_NORM: 0.
  WEIGHT_DECAY_BIAS: 0.
  BIAS_LR_FACTOR: 1
  CHECKPOINT_PERIOD: 1
  LRSCHEDULER: 'step'
  STEPS: (50,75,100)
  WARMUP_FACTOR: 0.
  WARMUP_EPOCHS: 20
  EVALUATE_PERIOD: 1
  PART_STRATEGY:
    ENABLED: True
    TEXTUAL_MODEL_LR_FACTOR: 0.1
    TEXTUAL_MODEL_WD_FACTOR: 0.1
    VISUAL_MODEL_LR_FACTOR: 0.1
    VISUAL_MODEL_WD_FACTOR: 0.1
TEST:
  IMS_PER_BATCH: 128
