MODEL:
  WEIGHT: "imagenet"
  FREEZE_TEXT: False
  FREEZE_VISUAL: False
  VISUAL_MODEL: "vit_base_patch16_224"
  TEXTUAL_MODEL: "bert"
  IMS_PER_BN: 64
  BERT:
    MAX_LENGTH: 64
    POOL: False
    OUTPUT_ALL: True
  NUM_CLASSES: 11003
  NUM_PARTS: 5
  RESNET:
    RES5_STRIDE: 1
    PRETRAINED: "pretrained/checkpoints/resnet50-19c8e357.pth"
    OUTPUT_ALL: False
  VIT:
    MODE: "all"
    CKPT: "pretrained/B_16-i21k-300ep-lr_0.001-aug_medium1-wd_0.1-do_0.0-sd_0.0--imagenet2012-steps_20k-lr_0.01-res_224.npz"
  EMBEDDING:
    EMBED_HEAD: 'baseline'
    FEATURE_SIZE: 512
    DROPOUT_PROB: 0.0
    LOSS_TYPE: [ "cmpm_loss", "cmpc_loss" ]
    LOSS_WEIGHT: [ 1., 1. ]
    VISUAL_POOL: 'avgpool'
    TEXTUAL_POOL: 'maxpool'
  LOSSES:
    CE:
      EPSILON: 0.1
INPUT:
  HEIGHT: 384
  WIDTH: 128
  FLIP:
    ENABLED: True
  PADDING:
    ENABLED: True
DATALOADER:
  EN_SAMPLER: "TrainingSampler"
DATASETS:
  TRAIN: ("cuhkpedes_train", )
  VAL: ("cuhkpedes_test", )
  TEST: ("cuhkpedes_test", )
  USE_ONEHOT: False
  USE_SEG: False
  USE_ATT: False
SOLVER:
  AMP: True
  IMS_PER_BATCH: 64
  NUM_EPOCHS: 100
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.00004
  WEIGHT_DECAY_NORM: 0.
  WEIGHT_DECAY_BIAS: 0.
  BIAS_LR_FACTOR: 1
  CHECKPOINT_PERIOD: 1
  LRSCHEDULER: 'step'
  STEPS: (50, 80)
  WARMUP_FACTOR: 0.
  WARMUP_EPOCHS: 10
  PART_STRATEGY:
    ENABLED: True
    TEXTUAL_MODEL_LR_FACTOR: 0.1
    TEXTUAL_MODEL_WD_FACTOR: 0.1
    VISUAL_MODEL_LR_FACTOR: 0.1
    VISUAL_MODEL_WD_FACTOR: 0.1
TEST:
  IMS_PER_BATCH: 64
